### ISSUE TITLE
Expanding Menu disappears on contract

### ISSUE THREAD

**Issue by yoiang** [kkarayannis/DKAExpandingMenu#1]
Hello! I've been checking out your control, I love how visually simple it is! 

I was wondering why the [superview.sendSubviewToBack](https://github.com/kkarayannis/DKAExpandingMenu/blob/fef2d617a774db40217ab8c4b0c72202e943d4bb/Classes/ios/DKAExpandingMenu.m#L175) call is in the completion block of the contract selector. Would it be possible to make it optional? I'd be happy to make a pull request with the change.

**Comment by kkarayannis** [comment]
Glad you like it! That's probably something left over from my own project and which shouldn't be there. Feel free to submit a pull request.

**Comment by kkarayannis** [comment]
Thanks for the great contributions!
