### ISSUE TITLE
Block callbacks for events

### ISSUE THREAD

**Issue by yoiang** [kkarayannis/DKAExpandingMenu#6]
Hey @kkarayannis!
Would you be open to including block callbacks that mirror functionality of the delegate's callback selectors? I'd be happy to make the pull request, just wanted to ask if it was worthwhile before I did.

**Comment by kkarayannis** [comment]
I don't think it's worth doing as it won't be adding anything other than one more way to do what the delegate does. I'd rather not complicate things.
I am willing to be convinced otherwise, so if there's a compelling use case feel free to reopen this issue.

**Comment by yoiang** [comment]
No worries!
